apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-dep
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: java
  template:
    metadata: 
      labels: 
        app: java
    spec:
      containers:
      - name: java-container
        image: akashjyothi/docker-jenkins-project:latest 
        ports:
        - containerPort: 8080     
          
